plugins{
    id 'java'
    id 'maven-publish'
}
//spring boot cloud and alibaba cloud version wiki:https://github.com/alibaba/spring-cloud-alibaba/wiki
ext{
    set("springCloudVersion", "2025.0.0")
    set("alibabaCloudVersion", "2023.0.1.2")
    set("dubboVersion", "3.3.5")
    set("commonsNetVersion", "3.9.0")
    set("mysqlConnectorVersion", "8.0.33")
    set("jjwtVersion", "0.11.5")
}
allprojects{
    group = 'com.cheeseocean'
    version = '1.0.0'

    repositories {
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        mavenLocal()
        maven {
            url = uri("https://maven.pkg.github.com/cheeseocean/CheesePackages")
            credentials {
                username = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
                password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
            }
        }
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'maven-publish'

    java {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    dependencies {
        testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.0'
        testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.7.0'
        testImplementation 'com.h2database:h2'
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
        implementation platform("org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}")
        implementation platform("org.springframework.boot:spring-boot-dependencies:3.5.3")
        implementation platform("com.alibaba.cloud:spring-cloud-alibaba-dependencies:${alibabaCloudVersion}")
//        implementation platform("org.apache.dubbo:dubbo-dependencies-bom:${dubboVersion}")
        //Spring Session
        implementation 'org.springframework.session:spring-session-data-redis'
        implementation 'io.lettuce:lettuce-core'
        //Alibaba Nacos
        implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery'
        //Validation
        implementation 'org.springframework.boot:spring-boot-starter-validation'
        //Spring Data
        implementation 'org.springframework.data:spring-data-jpa'
        //logback
        implementation 'ch.qos.logback:logback-classic'
    }

    tasks.register('apiJar', Jar) {
        from(sourceSets.main.output) {
            include 'com/cheeseocean/*/api/**'
        }
    }

    tasks.register('apiSourceJar', Jar) {
        from(sourceSets.main.allSource) {
            include 'com/cheeseocean/*/api/**'
        }
        archiveClassifier = 'sources'
    }

    publishing {
        repositories {
            maven {
                name = "GitHubPackages"
                url = uri("https://maven.pkg.github.com/cheeseocean/CheesePackages")
                credentials {
                    username = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
                    password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
                }
            }
        }
        publications {
            gpr(MavenPublication) {
                artifactId "${project.name}-api"
                //using gradle module:publish -Dapi.version or edit in gradle.properties
                version System.getProperty("api.version") ?: project.findProperty("${project.name}.api.version")
                artifact apiJar
                artifact apiSourceJar
                pom {
                    name = "${project.name} API Jar"
                    description = "CheeseMilk API dependencies"
                    url = "http://github.com/cheeseocean/CheeseMilk"
                    licenses {
                        license {
                            name = "The Apache License, Version 2.0"
                            url = "http://www.apache.org/licenses/LICENSE-2.0.txt"
                        }
                    }
                    developers {
                        developer {
                            id = "xxxcrel"
                            name = "xxxcrel"
                            email = "xxxcrel@gmail.com"
                        }
                    }
                }
            }
        }
    }

    test {
        useJUnitPlatform()
    }
}