spring:
  cloud:
    gateway:
      server:
        webflux:
          enabled: true
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: google-client-id
            client-secret: google-client-secret
          github:
            client-id: fde35d307ba5dcbaf79b
            client-secret: 0fefd4eacb906d3c79736239dd6ff47c76999835
  application:
    name: gateway
  profiles:
    active: dev
  data:
    redis:
      client-type: lettuce
      client-name: luttece
  jpa:
    open-in-view: false
  output:
    ansi:
          enabled: detect
  web:
    locale: zh_CN
  flyway:
    baseline-on-migrate: true
server:
  port: 7404
  servlet:
    session:
          cookie:
            name: SESSION
  error:
    include-exception: on
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG