dependencies {
    implementation 'jakarta.persistence:jakarta.persistence-api'
    implementation 'org.springframework.data:spring-data-commons'
    implementation 'org.springframework.security:spring-security-acl'
    implementation "commons-net:commons-net:${commonsNetVersion}"
    implementation "io.jsonwebtoken:jjwt-api:${jjwtVersion}"
    implementation "io.jsonwebtoken:jjwt-impl:${jjwtVersion}"
    implementation "io.jsonwebtoken:jjwt-jackson:${jjwtVersion}"
}