server:
  port: 7401

spring:
  application:
    name: core
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true